name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out your repository using git
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build.outputs.artifacts_dist }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist

      - name: Set up SSH key
        run: echo "${{ secrets.DEPLOYMENT_KEY }}" > ~/.ssh/id_rsa
        env:
          DEPLOY_KEY_PATH: ${{ github.workspace }}/.ssh/id_rsa

      - name: Set permissions for SSH key
        run: chmod 600 ${{ env.DEPLOYMENT_KEY}}

      - name: Add SSH config
        run: echo -e "Host github.com\n  IdentityFile ${{ env.DEPLOYMENT_KEY }}\n  LogLevel ERROR" >> ~/.ssh/config

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git remote set-url origin git@github.com:your-organization/code-oasis-website.git
          git checkout main
          git fetch
          git reset --hard origin/main
          git clean -f -d
          npm install
          npm run build
          git add .
          git commit -m "Auto-deploy to GitHub Pages"
          git push origin main
        env:
          DEPLOY_KEY_PATH: ${{ github.workspace }}/.ssh/id_rsa
